services:
  fullcycle-node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: fullcycle-node
    entrypoint: ["dockerize", "-wait", "tcp://mysql-db:3306", "-timeout", "20s", "node", "index.js"]
    networks:
      - nodenet
    volumes:
     - ./node:/usr/src/app
    tty: true
    depends_on:
     - mysql-db
  
  mysql-db:
    image: mysql
    command: --innodb-use-native-aio=0
    container_name: mysql-db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
    ports:
      - "3306:3306"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    entrypoint: ["dockerize", "-wait", "tcp://fullcycle-node:3000", "-timeout", "20s", "nginx", "-g", "daemon off;"]
    ports:
      - "8080:80"
    networks:
     - nodenet
    depends_on:
     - fullcycle-node
  
networks:
  nodenet:
    driver: bridge